FROM amazoncorretto:11-al2023-jdk
MAINTAINER Ramesh Ramachandran
EXPOSE 8080
WORKDIR /usr/local/bin
COPY ./trial-0.0.1-SNAPSHOT.jar trial.jar
CMD ["sh"]
# ENTRYPOINT ["java”,  “ -jar ", "./trial-1.0.0.jar"]
